// <auto-generated />
namespace WCF_Entity_Gyak.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TestValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestValues));
        
        string IMigrationMetadata.Id
        {
            get { return "201609111820414_TestValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
